version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stay-tuned
    ports:
      - "5432:5432"
    networks:
      - postgres
  smtp-server:
    container_name: smtp-server
    image: rnwood/smtp4dev:v3
    ports:
      - "8080:80"
      - "2525:25"
    networks:
      - smtp
  redis:
    image: redis:7.0.5-alpine
    ports:
      - '6379:6379'
    networks:
      - redis
  server:
    build:
      dockerfile: Dockerfile.server
    ports:
      - '3000:3000'
    environment:
        SERVER_PORT: 3000
        PG_CONN_STR: postgres://postgres:postgres@postgres:5432/stay-tuned
        SMTP_HOST: smtp
        SMTP_PORT: 2525
        MAIL_ADDRESS: foo@example.com
        REDIS_CONNECTION_STRING: redis://redis:6379
        QUEUE_NAME: price-advisor
        CLIENT_ADDRESS: localhost
        CLIENT_PORT: 8000
    depends_on:
      - postgres
      - redis      
    networks:
      - postgres
      - redis
  mail-sender:
    build:
      dockerfile: Dockerfile.mail-sender
    environment:        
        PG_CONN_STR: postgres://postgres:postgres@postgres:5432/stay-tuned
        SMTP_HOST: smtp-server
        SMTP_PORT: 25
        MAIL_ADDRESS: foo@example.com
        REDIS_CONNECTION_STRING: redis://redis:6379
        QUEUE_NAME: price-advisor
    depends_on:
      - server
      - postgres
      - redis
      - smtp
    networks:
      - postgres
      - redis
      - smtp
  client:
    build:
      dockerfile: Dockerfile.client
    environment:        
      CLIENT_PORT: 80
      SERVER_PORT: 3000
      SERVER_ADDRESS: server
      API_ENDPOINT: /api
    ports:
      - '8000:80'
    depends_on:
      - server
    networks:
      - backend
networks:
  postgres:
    driver: bridge
  redis:
    driver: bridge
  smtp:
    driver: bridge
  backend: 
    driver: bridge
